### ISSUE TITLE
Upgrade UI - Screen Home / Crypto

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1005]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1115%3A36209&t=lSq6WfQhrzPdUsuL-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1047-merge-build-0.8.1-1677006965970.zip

Please check:

- [ ] Add the empty token list screen & update %
![image](https://user-images.githubusercontent.com/102292476/220613086-7511ceca-bddb-4506-a1b0-fce379d7a2ea.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1047-merge-build-0.8.1-1677006965970.zip

Please check:

- [ ] Upgrade UI follow by design
![image](https://user-images.githubusercontent.com/102292476/220807338-eb7806c2-51c2-44b4-b543-889c7552e2b1.png)

Improve

- [ ] Reset repeat password when re-enter password

**Comment by ThaoNguyen998** [comment]
Version test: 

[_1055-merge-build-0.8.1-1677562303221.zip](https://github.com/Koniverse/SubWallet-Extension/files/10849616/_1055-merge-build-0.8.1-1677562303221.zip)

Please check: 

- [ ] Upgrade UI follow by design 


![Image](https://user-images.githubusercontent.com/117999489/221839160-dd9baa28-7a33-4208-b4f1-d4e672c8139d.png)



![Image](https://user-images.githubusercontent.com/117999489/221839194-42463f87-12f6-4288-ba98-dad7155c3cb9.png)

**Comment by saltict** [comment]
- [ ] Show incorrect Total balance on the "All accounts" when turn on Acala, Moonbeam network
![image](https://user-images.githubusercontent.com/102292476/222125960-b14e3b2c-2ab3-4c59-837a-a5caf78a25ca.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1090-merge-build-0.8.1-1679042310117.zip

- [ ] Incorect font-size of the Manage token list button
![image](https://user-images.githubusercontent.com/102292476/225875997-606c518a-39b3-4c7b-ae89-d3004625653b.png)

**Comment by sokol142** [comment]
- [ ] Show incorrect balance or do not show balance
- Show incorrect EQ, CRAB balance
   - EQ check with address: 5HbcGs2QXVAc6Q6eoTzLYNAJWpN17AkCFRLnWDaHCiGYXvNc
   - CRAB check with address: 0x3e25247CfF03F99a7D83b28F207112234feE73a6
![image](https://user-images.githubusercontent.com/102292476/227850110-837b0272-82da-4181-ae8c-59d87e16a814.png)
![image](https://user-images.githubusercontent.com/102292476/227873041-36d385a1-96a9-4e7c-8e15-bf0398d1fe61.png)

- Do not show GENS balance
   - Check with address: 5GdyPmQ8trkyeWRXaq6zjUJfB7mFzAz8Qc5e55sFkHXwUaHJ
![image](https://user-images.githubusercontent.com/102292476/227850226-7481caea-8000-478d-8ad6-d1b4c59996a9.png)

**Comment by sokol142** [comment]
- [ ] UI bug when scrolling then inspect
![image](https://user-images.githubusercontent.com/102292476/228120949-5f568bb3-1fb3-4318-8fa3-d6b950b7eba5.png)
