### ISSUE TITLE
Upgrade UI - Screen Settings / Master Password

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1012]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=842%3A53040&t=QB7ZXiO1e8uOeewa-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1047-merge-build-0.8.1-1677006965970.zip

Please check:

- [ ] Upgrade UI follow by design
![image](https://user-images.githubusercontent.com/102292476/220809297-3dc0a2c5-6c71-4119-abbc-b11f36826f04.png)


Improve

- [ ] Reset repeat password when re-enter password

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1678525608021.zip

Please check:
- [ ] Update the user flow when create/apply master password: https://www.figma.com/file/bynZeodGTmvwoPU2Ki2vEU/SubWallet---User-flow?node-id=29%3A837&t=XN8rAGjcbO6v7v26-4

- [ ] Incorrect flow create master password incase upgrade version
   - Actual: When user upgrade version then display the apply master password: https://www.loom.com/share/61c4a9bffef8474cb4f8e2801aba3a10
   - Expect: When user upgrade version then display the create master password
      - After created master password successfully then display the apply master password screen

Change wallet:

- [ ] Navigate to incorrect the screen in case change wallet
   - Actual: Back to Homepage
   - Expected: Navigate to the "Setting" screen
