### ISSUE TITLE
Upgrade UI - Screen Websitte Access (Authorized DApp List)

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1014]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1327%3A172805&t=i34VRSl9C0ltrIwf-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1678083121116.zip

Please check:

- [ ] Update UI follow by design
![image](https://user-images.githubusercontent.com/102292476/223624345-dda8056f-e59a-4700-9582-cfffb5c7600a.png)

- [ ] Add the filter button
- [ ] Add the filter popup

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1092-merge-build-0.8.1-1679311924409.zip

- [ ] Update UI follow by design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1331-50327&t=UNwa1AsDxD1rp00R-4
- [ ] Show incorrect counter in case add new account after connected
  Steps:
  1. Go to any EVM app (example: https://app.arthswap.org/#/swap)
  2. Connected wallet successfully
  3. Open the SubWallet extension
  4. Go to the Manage website access screen then observe the counter number of Arthswap
  5. Add a new Substrate account
  6. Back to the Manage website access screen then observe the counter number of Arthswap
  7. Go to the Website detail then count the account on the list

  Actual: Show incorrect counter 
![1014_BugCounter](https://user-images.githubusercontent.com/102292476/226543962-e85a92e1-11be-450c-abfb-4bf454e7d819.gif)
