### ISSUE TITLE
Upgrade UI - Screen Account / List

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1017]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=842%3A53043&t=dNIQeN3c8lmWPeVF-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1047-merge-build-0.8.1-1677006965970.zip

Please check:
**Select account screen** 

- [ ] Upgrade UI follow by Design
![image](https://user-images.githubusercontent.com/102292476/220828821-f8946769-6476-48c0-9654-c32335f4cd95.png)
![image](https://user-images.githubusercontent.com/102292476/220843293-a449ef4d-a0b1-4d47-86eb-78f594c3654a.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1090-merge-build-0.8.1-1679055190508.zip

Validation passed.
![image](https://user-images.githubusercontent.com/102292476/226084890-51db7446-7370-49ac-b843-3f6694f614de.png)
![image](https://user-images.githubusercontent.com/102292476/226084903-8293e0fa-5851-4b30-99f0-d9b72b6365f8.png)
