### ISSUE TITLE
Upgrade UI - Screen Account / Add

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1018]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=842%3A53042&t=QB7ZXiO1e8uOeewa-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1047-merge-build-0.8.1-1677006965970.zip

Please check:
**Select account screen** 

- [ ] Upgrade UI follow by Design
![image](https://user-images.githubusercontent.com/102292476/220828821-f8946769-6476-48c0-9654-c32335f4cd95.png)


**On the create new account**

- [ ] Still enable button confirm when do not select account type
![image](https://user-images.githubusercontent.com/102292476/220810179-47f7f513-bfaa-410e-a91b-33e400942cdc.png)

- Expected: If do not select account type -> Disable button Confirm

- [ ] Sequence number of seed phrase

![image](https://user-images.githubusercontent.com/102292476/220809678-5625409f-6d38-4d3c-9c65-fa86c531316f.png)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1055-merge-build-0.8.1-1677562303221.zip

Please check: 

- [ ] Disable button in case don't select account type

![Image](https://user-images.githubusercontent.com/117999489/222100066-d49448da-1f08-4ccf-b30e-beb61a69f80e.png)

- [ ] Add checkbox Import multiple accounts from this seed phrase in Import from seed phrase screen


![Image](https://user-images.githubusercontent.com/117999489/222108567-f6c6df17-1c4d-4851-b4d1-0486ae78362b.png)

- [ ] Upgrade UI for design

![Image](https://user-images.githubusercontent.com/117999489/222118049-7fbacf9a-319a-438f-b89d-9723cc261cd4.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1678083121116.zip

- [ ] Update format account after enter address
![image](https://user-images.githubusercontent.com/102292476/223611011-7db61673-3c21-4bad-821d-6dbdc5f85133.png)

**Comment by sokol142** [comment]
Version test: https://drive.google.com/drive/folders/1T4V5FUrgmeSGKiQdlQ6yGbDK0wxIh4LF?usp=share_link
Please check:
Handle cases related to Ledger account:
- [ ] Do not show more than 20 account when attach account
- [ ] Do not display tokens other than those that Ledger account is supporting:
- List token on the token tab
- Receive: automatically show the QR code screen of the supported token
- Transfer: fixed the supported token
- Buy token: fixed the supported token
- Staking action: fixed the supported token

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1083-merge-build-0.8.1-1678780061728.zip
Please check:

- [ ] Update UI incase import single account by JSON file follow by design:  https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=2406%3A66561&t=7YfOwmefFI5o4Th8-4

**Comment by sokol142** [comment]
Version test:

- [ ] Handle case attach Ledger account on the first time when user standing on the popup extension
- [ ] UI bug
![image](https://user-images.githubusercontent.com/102292476/225292744-c9bef078-6b44-42cc-b784-f6a25853726c.png)

- [ ] Still show error message when back to the previous screen
![image](https://user-images.githubusercontent.com/102292476/225298375-02bfd2ee-549e-4817-89d3-3a62493ce3c2.png)

**Comment by S2kael** [comment]
- [ ] Incorrect color of the Scan button (update design system, need update in library)
![image](https://user-images.githubusercontent.com/102292476/225305459-c20f9c07-5633-447c-b79a-433b40625744.png)

**Comment by sokol142** [comment]
Version test:

- [ ] Navigate to the incorrect screen in case create new account from Welcome screen
- Actual: Navigate to the Create new account
- Expected: Navigate to the Select account type popup
![1018_bugNavigate](https://user-images.githubusercontent.com/102292476/225557976-b70646a8-b3db-409f-9883-9cab15fcce35.gif)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1090-merge-build-0.8.1-1679055190508.zip

- [ ] Update style on the Imported account list when import multi account by JSON file 
![image](https://user-images.githubusercontent.com/102292476/226083391-47f615d0-958a-404c-a390-be1c5f9d983c.png)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1679306339002.zip

- [ ] Re-check attach account Connect Keystone device 
Actual: Do not show message Invalid QR


![Image](https://user-images.githubusercontent.com/117999489/226586642-29da03cc-e2bd-4e07-bced-7096412b4a54.gif)
