### ISSUE TITLE
Upgrade UI - Modal Select Account

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1020]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1246%3A34085&t=dNIQeN3c8lmWPeVF-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1047-merge-build-0.8.1-1677006965970.zip

Please check:

- [ ] Upgrade Ui follow by design

![image](https://user-images.githubusercontent.com/102292476/221076762-f5995cc6-fde9-44d4-956c-0e31e3466c94.png)

- [ ] Reset search box after selected item
Steps:
1. Open the Select account popup
2. Input key search on the search box
3. Select any item on list -> close popup select account
4. Re-open the Select account popup then observe list account displayed
Actual: Still search
Expect: Reset search box after selected item
![UpgradeUI_SelectAccount](https://user-images.githubusercontent.com/102292476/221078183-bc811156-6b22-4d4d-b2a3-abcea28f9d88.gif)

**Comment by ThaoNguyen998** [comment]
Version test: 

[_1048-merge-build-0.8.1-1677232673460.zip](https://github.com/Koniverse/SubWallet-Extension/files/10831041/_1048-merge-build-0.8.1-1677232673460.zip)

Please check: 

- [ ] Upgrade Ui follow by design


![Image](https://user-images.githubusercontent.com/117999489/221355492-801300f0-2327-4e9f-9b12-f0910cb32fb1.png)
