### ISSUE TITLE
Upgrade UI - Login

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1026]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1172%3A85163&t=dNIQeN3c8lmWPeVF-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1048-merge-build-0.8.1-1677232673460.zip
Please check:

- [ ] Upgrade ui follow by design
![image](https://user-images.githubusercontent.com/102292476/221737513-3de93a8a-bdcd-48fb-b824-ab3d7babb48a.png)

- [ ] User must be remove the each character If user input wrong password 
- Expect: Automatically remove old password when user re-enter password

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1087-merge-build-0.8.1-1678871780217.zip

Please re-check background

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1087-merge-build-0.8.1-1678951713211.zip

Validation passed.
![image](https://user-images.githubusercontent.com/102292476/225590229-55ddd043-6a09-4fc9-aa24-98720d9d8bab.png)
![image](https://user-images.githubusercontent.com/102292476/225590349-14175817-7eb3-455b-96c3-b62333c0e5d8.png)
