### ISSUE TITLE
Upgrade UI - Screen Settings / Migrate to Master Pasword

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1027]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=818%3A42645&t=QB7ZXiO1e8uOeewa-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1047-merge-build-0.8.1-1677006965970.zip

Please check UI screen:

- [ ] Upgrade UI follow by design
![image](https://user-images.githubusercontent.com/102292476/220812446-a2a0dc2d-c9c6-417f-ab57-e601bcc8b7c2.png)

![image](https://user-images.githubusercontent.com/102292476/220822669-5489924c-b519-4184-a962-d0ef4da33051.png)

- [ ] Re-check 
![UpgradeUI_ApplyMasterPassword](https://user-images.githubusercontent.com/102292476/220823055-e0b91aca-e943-4265-b5b6-fe2c455b2031.gif)

----------
Improve
- [ ] Reset information in case back to migrate again

---------
Test later: Flow migrate master password

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1055-merge-build-0.8.1-1677649126675.zip

- [ ] Redirect user to the Apply master password in case import account by JSON file
Pre-condition: 
- Created master password successful
- Have account on the wallet

Steps:
1. On the Homepage
2. Go to the Select account screen
3. On the Select account screen, click on the "Import" button then select Import by JSON file 
4. Perform imported account by JSON file successfully
5. Observe the screen displayed

Actual: Do not navigate the Apply master password screen after importing account by JSON file successfully
Expected: After importing account by JSON file successfully, redirect user to the Apply master password screen.

**Comment by sokol142** [comment]
- [ ] Show counter of accounts to which the master password needs to be applied is incorrect
  - Actual: Count total account
  - Expect: Count total accounts need to apply master password
![ApplyMasterPassword](https://user-images.githubusercontent.com/102292476/227894391-23ab58b5-a5ab-4cd3-b50a-b12d07a1e65d.gif)
