### ISSUE TITLE
Upgrade UI - Receive Token Screen

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1054]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1224%3A144919&t=i34VRSl9C0ltrIwf-4
- [x] UI for ReceiveAccountSelect
- [x] UI for ReceiveTokenSelect
- [x] UI for ReceiveModal
- [x] Logic get Receive Qr and address

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1678083121116.zip

Please check:

- [ ] Update UI follow by design
![image](https://user-images.githubusercontent.com/102292476/223400353-a72336b1-c693-4471-acfa-a4317248d294.png)

- [ ] Do not get address when user standing on the Token detail screen
- Expected: 
Standing on the specific account:
+ Token detail screen have multi token -> Show the select token screen
+ Token detail screen has a token -> Show the Your QR code screen
Standing on the All accounts:
+ Token detail screen have multi token -> Show the select account screen then show the select token screen
+ Token detail screen has a token -> Show the select account screen then Show the Your QR code screen

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1090-merge-build-0.8.1-1679055190508.zip

Validation passed for cases:
- Get address in case All account
- Get address in case Specific
- Get address when stand on the Token Detail screen
- Token displayed in case switch account
- Search token
- Copy address
- View account on explorer

Test later: back action on the screens
