### ISSUE TITLE
Integrate Banxa for fiat on-ramp features

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#1084]
**Is your feature request related to a problem? Please describe.*

SubWallet will be one of the curators for this proposal: https://kusama.polkassembly.io/post/2513, which aims at having more parachains supported in Banxa fiat on-ramp solution. 

Currently, Banxa is actively supporting the Polkadot ecosystem and working closely with parachains. Please integrate Banxa solution. 

See this for API documentation: https://docs.banxa.com/docs

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1443-build-1.0.6-0-2023-05-25T10-36-59UTC.zip

Please check:

- [ ] Logo style

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/348b7e43-500f-454f-8a46-36ede334f0e0)

- [ ] Remove default value on the Select service 
   - Actual: Default value = Transak
   - Expect: Show placeholder "Select supplier" to choose supplier

- [ ] Give me the list token that supported by Banxa

I'm cannot testing, because i don't receive the code to verify on Banxa

**Comment by Sokol142196** [comment]
@ThaoNguyen998 => List token supported by Banxa: 

[tokenList_Banxa.csv](https://github.com/Koniverse/SubWallet-Extension/files/11673905/tokenList_Banxa.csv)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1443-build-1.0.8-2023-06-08T09-41-51UTC.zip

Validation passed on the test environment with tokens:
- DOT
- KSM
- GLMR
- ETH
- MOVR

**Comment by Sokol142196** [comment]
@S2kael Improve UI: Display supplier list by selected token
- If selected token is supported by only 1 supplier -> Auto-fill default supplier
- If selected token is supported by multiple suppliers -> Enable the supplier and allow user select supplier

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1443-build-1.1.4-2023-07-27T10-34-47UTC.zip

Validation passed
![1084_Validation](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/faa61bec-4441-4c4b-9921-376c81725189)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1443-build-1.1.5-2023-08-01T03-18-52UTC.zip

Validation passed
