### ISSUE TITLE
Add ArtZero API

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#1112]
Support ArtZero API to provider better NFT experience on Aleph Zero

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1113-merge-build-0.8.3-1-1680175884408.zip
Please check this issue

- [ ] Do not show some NFT
   - Reproduce the behavior with the address: 5GC438eifKW2A42KRhnawiDkdEdwRW8Z8hw9oTuwzJzxVzAg
   - NFT contract address: 5H8H2upyuxUAzU1NcHzt97DhTqQkmcp3u4quaM246uHBm5fL (Aleph Zero testnet)
![image](https://user-images.githubusercontent.com/102292476/229009041-2939ae3e-350e-45b3-a238-d331d0658a5b.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1113-merge-build-0.8.3-1-1680236811894.zip

Validation passed!
![image](https://user-images.githubusercontent.com/102292476/229033461-e465aa5f-71a3-4b01-872c-c03311957a1f.png)

**_Note for testing:_**
- When using the API's ArtZero, some data is missing (root cause: listed not yet) 
-> Solution: ArtZero handles this case => Retest later.
