### ISSUE TITLE
Address Book Feature

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1219]
Design: 
- Address book: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3977-171914&t=KiBKKd8g0rKCHTyE-4
- Manage address book:  https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1671-53572&t=KiBKKd8g0rKCHTyE-4

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1192-build-1.0.2-1-2023-04-14T11-29-45UTC.zip

- [ ] Update placeholder on searchbox
![image](https://user-images.githubusercontent.com/130966515/232665874-045cb25b-0f2c-4386-94e4-a9634f668ea8.png)

- [ ] Show an error message when the user clicks on the "Address book" button in the Send NFT screen
![image](https://user-images.githubusercontent.com/130966515/232665929-c4f546b2-6b1c-4065-9a9f-41eb6dbc1f78.png)

- [ ] Update the format of the address 
![image](https://user-images.githubusercontent.com/130966515/232667121-b1faf5a8-b173-4892-8fc6-5a4512d4773f.png)

- [ ] Update padding on the "Manage address book" follow by design
![image](https://user-images.githubusercontent.com/130966515/232666066-ceff0494-1871-424e-baf2-c6df5ec3a8ee.png)

- [ ] Add the remove contact action
- [ ] UI bug when scrolling on the Manage address book screen
![1219_bugUI](https://user-images.githubusercontent.com/130966515/232666254-ef300bec-b178-4852-b1b6-b87fe0913433.gif)

- [ ] Redirect the incorrect screen when the user clicks on the Back button 
   - Actual: Back to the Homepage screen
   - Expect: Back to the Setting screen

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1192-build-1.0.2-1-2023-04-18T09-56-46UTC.zip

Please check:

- [ ] Still show the error message of the previous request
![1219_UIbug](https://user-images.githubusercontent.com/130966515/233030820-76e20a97-d59b-4f61-b56e-da44ae5460a2.gif)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1192-build-1.0.2-1-2023-04-19T11-57-55UTC.zip

- [ ] Bug typo
![image](https://user-images.githubusercontent.com/130966515/233266160-a6ab532d-1f76-4e52-84f2-0fd6f6c5981f.png)
