### ISSUE TITLE
Error submitting transaction on Astar EVM due to gas fee calculation

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#2255]
#### Describe
Error when executing a transaction on Astar EVM network.

#### Reason
- In checking...
- Maybe an error by the gas fee

**Comment by S2kael** [comment]
### Reason
Because the gas price changed over time, special with Astar, it changed per block. When submitting, the gas price in the data (taken when creating the transaction) is too low if compared with the block. So the transaction will be rejected or failed.

### Solution
With Astar, multi the gas price with a number (1.05) to make sure the transaction is submitted successfully.

### Note
Hotfix with Astar only, please follow with other networks.
