### ISSUE TITLE
Integrate SubWallet with EVM Dapp

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#235]
## Overview
SubWallet now support EVM Account (H160) and also can interact with EVM via web3.js but now package `extension-dapp` and `extension-inject` need to be improvove for devliver these feature with the way like MetaMask done for browser DApp.

### EVM DApp methods
Here is most basic feature we need to provide for EVM DApp.
- EVM (H160) Account list 
- Sign EVM transactions/data
- Add (import) EVM chain
- Import ERC20 / ERC721 tokens
- Connect to DApp
- And another feature like MetaMask

### How to MetaMask extension interact with DApp?
MetaMask will publish a provider to browser window with name ethereum. DApp interact with MetaMask extension via this object.
- DApp will use this ethereum object by `ethereum.request` eg:`ethereum.request({ method: 'eth_requestAccounts' });`
- DApp also listen MetaMask change via `ethereum.on('event_name', callback: () => {}))`.
- [Read more](https://docs.MetaMask.io/guide/getting-started.html)

### Difference between MetaMask and SubWallet
- Chains and accounts
  - MetaMask will connect to single chain and select only one account at a time.
  - SubWallet with connect to multi chain and can select more than one account at a time.
  - These differences cause some in the way DApp interaction with extensions
- Signatures
  - MetaMask support Ethereum signature.
  - SubWallet support both Substrate signature and Ethereum signature

## Solution
We aim to provide an interface similar to MetaMask to reduce integration effort from products that already have supported MetaMask but because some diffrerences they will not be the same.

### Concept:
![image](https://user-images.githubusercontent.com/11567273/174527261-3a2fff58-31f2-4167-acdd-8562d3a977eb.png)
- With concept 2 we with deliver evm methods by deference object with substrate methods. 
- This concept require developer to add new wallet interface but allow us to develop most similar interface with MetaMask.
- We will public to `window.ethereum` if MetaMask to other wallet not exists
- We don't want user need change their habits and DApp developer update their code too much for support SubWallet, so web wil try to make interaction with `SubWallet` similar to `ethereum` of `MetaMask`, SubWallet will interact to account and chains like the way metamask do when interact with DApp via evm provider.

## Design Interface
- Substrate interface: keep normal with name subwallet-js like current
- EVM interface: 
  - Support single account and single chain mode (Auto select first allowed account and request chain with a confirmation popup)
  - Emit `accountChanged` and `chainChanged` events.
  - Support provider.request({method, params})

### Change on SubConnect
- [x] Migrate to mutipackages architech
- Create new `@subwallet/wallet-connect` in repository SubWallet: A connect lib support both Substrate and EVM interface.
  - [x] Basic connect features replace current wallet packages
  - [x] Allow inject new Wallet not required modify packages
  - [x] Update SubConnect with new interface and features

- [x] Use wallet-connect instead of current lib/wallets
- [x] [Examples of MetaMask on SubConnect](https://github.com/Koniverse/SubConnect/issues/6)
- [x] Example of SubWallet - EVM Connect 

### Change on SubWallet
- Create basic features:
  - [x] Update authorize screeen
    - [x] EVM
    - [x] Substrate
    - [x] Both
  - Connect to wallet
    - [x] eth_requestAccounts
    - [x] eth_accounts
  - [x] Support `provider.on(eventName, callback)`
    - [x] accountsChanged
    - [x] chainChanged
      - [x] Update current chain management
    - [x] connect
    - [x] disconnect
  - [x] Support `provider.request(method, param)`
  - Import metadata
    - [x] wallet_addEthereumChain
    - [x] wallet_switchEthereumChain
  - Sign data or send transaction
    - [x] eth_sign
    - [x] eth_sendTransaction
    - [x] eth_personalSign
    - [x] eth_signTypedData
    - [x] popup sign confirmation
  - Get/Subscribe/Send data
    - [x] eth_sendTransaction
    - [x] eth_signTranaction Popup
    - [x] eth_getBalance
  - Permission
    - [x] Get permission
    - [x] Request permission 
Improvement:
- More improvement will be list and and handle in #357

**Comment by sokol142** [comment]
Please check issues:

- [ ] Still display Account Substrate on the Request Permission screen: https://prnt.sc/qxRPFUVqMGYA 
- [ ] Do not Transaction History when Send Transaction from DApp
- [ ] Bug happens when switch to All Account/ Forget Account: https://prnt.sc/eQpfE9wRVLl1 
- [ ] Disconnect Account when click on Cancel button on the Request Permission screen although before, account connected successfully.
![235_DisconnectAccount](https://user-images.githubusercontent.com/102292476/173721384-c2fd78e4-2d80-4bcb-85c5-fcd2c7835ae4.gif)
- [ ] Check performance in case Connect/Disconnect Network when user interactive with DApp
- [ ] Display Network incorrect when user Switch to account, that have another current network
![235_SwitchNetwork](https://user-images.githubusercontent.com/102292476/173722165-0cd708a6-1b1c-4f29-b350-e9d2e53ec579.gif)
- [ ] Do not send transaction
![image](https://user-images.githubusercontent.com/102292476/173722277-0adc4e62-4f35-49c3-98ec-b2fc4ea003e9.png)
- [ ] Do not showing Avatar account when add new account: https://prnt.sc/8Vh0fe27AeQX 
- [ ] Support Send Transaction/Sign for Ledger Account/QR Account

Some improve:
- Don't allow the user to click the button more than once
- UI: https://prnt.sc/Rx92WdQx7Vye, https://prnt.sc/nyDSP6SBbIXh

**Comment by sokol142** [comment]
- [ ] Bug happens when click on Add Network/Switch Network button in case Current Account allow use any chain or inactivate network
![image](https://user-images.githubusercontent.com/102292476/174059763-f1563ea5-efce-4851-a9f7-7433b8281f10.png)

**Comment by sokol142** [comment]
Some bug UI:
![image](https://user-images.githubusercontent.com/102292476/174221505-9995972d-ea1f-44ff-87c3-af558049cd27.png)
![image](https://user-images.githubusercontent.com/102292476/174221662-a7b6f1e2-2b51-429a-98df-c7e4c6f052e7.png)
![image](https://user-images.githubusercontent.com/102292476/174221708-ae220f7d-f1fa-4a05-aa27-f43a4762c26d.png)
![image](https://user-images.githubusercontent.com/102292476/174224735-9e8301fe-cbc5-498b-8f44-52723407cc5f.png)
