### ISSUE TITLE
WebApp - Re-check bug when have multi connect with WalletConnect

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2778]
**Describe the bug**
Re-check bug when have multi connect with WalletConnect

**To re-produce the bug**
Actual: Show message

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/0133fda1-50b1-49f0-98a3-d1e064c22f55)

**Comment by Sokol142196** [comment]
- [ ] Waiting content to update

**Comment by haiyenvu23** [comment]
Version test : https://ac3f95f8.subwallet-webapp.pages.dev/
Validation passed in case : 
- Show message in case error due to client 


![Image](https://github.com/user-attachments/assets/8cf021a9-2ed5-47b7-9788-7a6b6e6bd5c4)

- Show message in case error due to server


![Image](https://github.com/user-attachments/assets/8e10eb37-3dc0-49f6-9966-948914e34732)

- Handle for extension => Related to issue https://github.com/Koniverse/SubWallet-Extension/issues/3456
