### ISSUE TITLE
Update chainlist

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#3040]
- [x]  Krest: Added chainBalanceSlug

- [x]  Ajuna: Added URL explorer and chainBalanceSlug

- [x]  Crust parachain: Has chainBalanceSlug but cannot detect balance

- [x]  Darwinia 2: Has chainBalanceSlug but cannot detect balance

- [x]  Polkadot Bridge Hub: Add URL explorer and chainBalanceSlug

- [x]  Parallel: Remove URL explorer because Subscan is no longer supported

- [x]  Kusama Bridge Hub: Added URL explorer and chainBalanceSlug

- [x]  Crab2 Parachain: Addition of chainBalanceSlug

- [x]  Integritee Network: Has chainBalanceSlug but cannot detect balance

- [x]  Mangata X: Added chainBalanceSlug

- [x]  Crust Mainnet: Addition of chainBalanceSlug

- [x]  Dock: Added chainBalanceSlug

- [x]  Sora parachain: Added chainBalanceSlug

- [x]  Subsocial : Added URL explorer  :  https://explorer.subsocial.network/

**Comment by bluezdot** [comment]
https://github.com/Koniverse/SubWallet-ChainList/issues/219

**Comment by bluezdot** [comment]
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/218
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/220

**Comment by bluezdot** [comment]
- https://github.com/Koniverse/SubWallet-ChainList/issues/220

Pendulum
- [ ] XLM
- [ ] EURC
- [ ] BRL
- [ ] AUDD
- [ ] NGNC
- [ ] USDC
- [ ] HDX
- [ ] GLMR
- [ ] PINK

**Comment by bluezdot** [comment]
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/221

**Comment by ThaoNguyen998** [comment]
Version test:  http://file.cdmteck.com/s/ggokNQgPwKB2PdM

- [ ] Update price id for AUDD.s

**Comment by ThaoNguyen998** [comment]
Version test: http://file.cdmteck.com/s/ggokNQgPwKB2PdM
Validation passed.
- Update chain info: 
  - Krest: Added chainBalanceSlug
  - Ajuna: Added URL explorer and chainBalanceSlug
  - Crust parachain: Has chainBalanceSlug but cannot detect balance
  - Darwinia 2: Has chainBalanceSlug but cannot detect balance
  - Polkadot Bridge Hub: Add URL explorer and chainBalanceSlug
  - Parallel: Remove URL explorer because Subscan is no longer supported
  - Kusama Bridge Hub: Added URL explorer and chainBalanceSlug
  - Crab2 Parachain: Addition of chainBalanceSlug
  - Integritee Network: Has chainBalanceSlug but cannot detect balanc
  - Mangata X: Added chainBalanceSlug
  - Crust Mainnet: Addition of chainBalanceSlug
  - Dock: Added chainBalanceSlug
  - Sora parachain: Added chainBalanceSlug
  - Subsocial : Added URL explorer : https://explorer.subsocial.network/
- Add support for CESS testnet 

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/7770f48d-95f8-4df5-a7a7-8b164c45852e)

- Add support for Hyperbridge (Nexus)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/12340fd4-c3ba-427d-8267-d3924b18ad06)

- Add support for BOB and tokens on BOB

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/bdc644fd-ddcd-4bb1-b318-1b461a485d07)
