### ISSUE TITLE
Research Uniswap price impact

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3269]
We need to calculate price impact for swaps on Asset Hub to warn users

**Comment by nampc1** [comment]
https://calculator.academy/price-impact-calculator/
https://stackoverflow.com/questions/74282316/uniswap-v2-pool-priceimpact
https://support.uniswap.org/hc/en-us/articles/8643794102669-Price-Impact-vs-Price-Slippage
https://dailydefi.org/articles/price-impact-and-how-to-calculate/
https://stackoverflow.com/questions/74282316/uniswap-v2-pool-priceimpact
https://medium.com/@arian.web3developer/everything-about-price-impact-slippage-rate-and-deadline-in-dex-swaps-explained-on-uniswap-dex-7f700ffa3948
https://blog.uniswap.org/uniswap-v3-math-primer
https://blog.uniswap.org/uniswap-v3-math-primer-2
https://medium.com/luchadores-chronicles/how-to-calculate-price-impact-b4c87d8b10ed

**Comment by bluezdot** [comment]
https://stackoverflow.com/questions/74282316/uniswap-v2-pool-priceimpact](https://stackoverflow.com/questions/74282316/uniswap-v2-pool-priceimpact)  

- x token A; y token B; k = x * y; rate = x/y. x,y,k is known
- swap m token A to n token B. m is known
- x' = x + m
- y' = k / x' (Because x' * y' must also equal to k)
- n = y - y'
- PI = n / y'

=> Finally: PI = n / y' = (y - y') / y' = (y - k / x') / (k / x') = (y - k / (x + m)) * (x + m) / k
= (y * (x + m) - k) / k = y * (x + m) / k - 1

**Comment by bluezdot** [comment]
- (m/n) / (x/y) - 1
- m/n = actual_rate
- x/y = market_rate
PI = actual_rate/market_rate - 1

**Comment by Sokol142196** [comment]
Version test: https://9dcf8574.subwallet-webapp.pages.dev/
Validation passed in case:
- Show low liquidity warning with Price impact < 0.15 %
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/954fdf69-181e-4637-8863-a52e19361f0b)

-----
Re-check:

- [ ] Formula of price impact
- [ ] Compare with https://app.dotacp.mvpworkshop.co/swap
