### ISSUE TITLE
Copy Account address although don't click copy address button when user click on Manage Account icon

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#336]
**Description the bug**
Copy Address Account when click on Manage Account

**To reproduce:**
Steps:
1. Open the extension
2. Go to Import Account
3. Copy the SeedPhase & Paste to "Mnemonic Seed" field
4. Input valid all data & created account successfully
5. Click on Manage Account icon
6. Then paste value on other area & check this value

**Actual:** Automatically copy account address although don't click copy address button
**Expect:** When user click on Manage Account icon, do not copy account address
![Image](https://user-images.githubusercontent.com/102292476/172135079-3dff70e4-bcc9-494c-95e7-80cdb274c111.gif)

**Comment by saltict** [comment]
This bug is caused by clicking the settings menu, this action also clicks on the Identicon (Account avatar) and copies its address.
![image](https://user-images.githubusercontent.com/11567273/179348461-dfc6911e-6726-4f6c-885c-30e5c426e160.png)
The solution is to create a mask on the Identicon of the settings menu button.

**Comment by sokol142** [comment]
Validation passed!
![336_validationpassed](https://user-images.githubusercontent.com/102292476/179483265-3f3fa63c-f0ab-4e81-9c27-42bebbe4173a.gif)
