### ISSUE TITLE
Update Ledger support for chains with updated runtime

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3884]

**Comment by PDTnhah** [comment]
Chains with updated runtime: 

- Polkadot:
    - Energy Web X
    - frequency
    - hyperbridge
    - invarch
    - polkadotPeople
    - acala
    - nodle
    - pendulum

- Kusama:
    - amplitude
    - karura

**Comment by haiyenvu23** [comment]
Validation passed in case : 
- Check when receive token 

![Image](https://github.com/user-attachments/assets/3e9ab8c9-7c23-4c10-84bf-ce62c9bd6917)

- Check when send token from normal account to ledger account
![Image](https://github.com/user-attachments/assets/6b50c959-757b-460d-bfe2-ec613f62c063)

- Check when send token from ledger account to normal account

![Image](https://github.com/user-attachments/assets/20a1ce1e-466c-458e-aed4-534f91a07054)

- Check sign transaction with polkadot js
- Check when perform stake => Can't reproceduce because don't enough balance
