### ISSUE TITLE
XCM transfer support for Relaychain to Parachains

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#411]
**Is your feature request related to a problem? Please describe.**
Refer: #35
XCM transfer support for Relaychain to Parachains

- [x] DOT: Polkadot -> Astar
- [x] DOT: Polkadot -> Acala
- [x] DOT: Polkadot -> Moonbeam
- [x] KSM: Kusama -> Moonriver
- [x] KSM: Kusama -> Shiden
- [x] KSM: Kusama -> Karura
- [x] xcDOT: Moonbeam -> Polkadot
- [x] DOT: Acala -> Polkadot
- [x] DOT: Astar -> Polkadot
- [x] xcKSM: Moonriver -> Kusama
- [x] KSM: Shiden -> Kusama
- [x] KSM: Karura -> Kusama

Please update more XCM channels via this link: https://dotsama-channels.vercel.app/#/

**Comment by NamPhamc99** [comment]
Update: Add support for
- [ ] Moonbeam -> Acala
- [ ] Moonriver -> Karura

**Comment by NamPhamc99** [comment]
Update: Logic completed

- [ ] Transfer from a parachain -> a parachain
- [ ] Transfer from a parachain -> relaychain
- [ ] Transfer from relaychain -> parachain

**Comment by NamPhamc99** [comment]
aUSD integration will be released sooner
Refer to #472 for more details

**Comment by sokol142** [comment]
**Bugs happens when transfer Moonbeam -> Acala**
- [ ] Incorrect transaction history
- [ ] Not show transaction history when click on View Transaction button on the Transfer Result
![image](https://user-images.githubusercontent.com/102292476/182132152-84228e85-1f20-44fe-956b-d426d764e373.png)
**Bugs happens when transfer Moonriver -> Karura**  (see file attachment: https://www.loom.com/share/60ad9a9651d84b47845a9b74e11cac0c)
- [ ] Incorrect transaction history
- [ ] Not show transaction history when click on View Transaction button on the Transfer Result (tx: https://moonriver.moonscan.io/tx/0x79a441da1c80a3ab5a8df9ead4e694b9b2693f7de5498833bc874ae5d45fd876)
- [ ] Not receive KAR

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./488-merge-build-0.5.3-1659588217997.zip

Validation failed for case:
- [ ] Astar (aUSD) -> Acala (aUSD)

Validation pass for cases:

- [ ] 1. Acala (ACA) --> Moonbeam (xcACA)
- [ ] 2. Acala (aUSD) --> Moonbeam (xcaUSD)
- [ ] 3. Moonbeam (xcaUSD) --> Acala (aUSD)
- [ ] 4. Acala (aUSD) --> Astar (aUSD)
- [ ] 5. Acala (aUSD) --> Astar - EVM (aUSD)
- [ ] 6. Karura (aUSD) --> Shiden (aUSD)
- [ ] 7. Karura (aUSD) --> Shiden - EVM (aUSD)
- [ ] 8. Shiden (aUSD) -> Karura (aUSD)
- [ ] 9. Karura (KAR) --> Moonriver (xcKAR)
- [ ] 10. Karura (aUSD) -> Moonriver (xcaUSD)
- [ ] 11. Moonriver (xcAUSD) --> Karura (aUSD)
- [ ] 12. Kintsugi (KINT) --> Moonriver (xcKINT)

File record validation:

**Comment by NamPhamc99** [comment]
Phala XCM:
https://subbridge.io/

**Comment by sokol142** [comment]
- [ ] Add a warning about the risk of losing tokens when making xcm transfers

**Comment by NamPhamc99** [comment]
More XCM transfers will be updated in later issues
