### ISSUE TITLE
Add other EVM chains

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#426]
[x] Support HTTP endpoint for EVM Network

### Ethereum Mainnet:

- RPC URL: https://mainnet.infura.io/v3/
- Chain ID: 1
- Currency Symbol: ETH
- Block Explorer URL: https://etherscan.io 

### Binance Smart Chain:

- RPC URL: https://bsc-dataseed.binance.org/
- Chain ID: 65
- Currency Symbol: BSC
- Block Explorer URL: https://bscscan.com

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./727-merge-build-0.6.7-1-1665737841969.zip

Please check issue:

- [ ] Add the block explorer
- [ ] Bug happens when config network

![Image](https://user-images.githubusercontent.com/102292476/195839437-f542eb6e-1b10-4a0c-b745-c0662354c781.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./727-merge-build-0.6.7-1-1666089402506.zip

Validation passed
_Notes: Only support: view balance & send fund_
