### ISSUE TITLE
Discussion about the unstake-withdraw flow and feedback staking feature

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#504]
**Description:**
Discussion about the unstake-withdraw flow

**Comment by hatrangkoni** [comment]
Two tasks regarding staking that users need/would like to do: 
1. Unstake from (denominate) one validator/collator/dApp and stake for (nominate) another. Right now one has to unstake, wait for the withdrawal period and withdraw before being able to stake again. Very inconvenient. 
2. Withdraw. Would be nice if users can unstake and the funds will automatically be deposited in their transferrable balance after the waiting period.

**Comment by hatrangkoni** [comment]
**Staking screen**: I would like to have the option to sort out validators/collators/dApps that are oversubscribed and require a minimum stake higher than what I have. Aka I would like to sort out which one I am eligible to stake for in order to earn rewards
<img width="453" alt="Screen Shot 2022-07-30 at 15 01 11" src="https://user-images.githubusercontent.com/103566796/181886239-6ed4cc73-342c-450b-a712-6c55296e661e.png">
.

**Comment by sokol142** [comment]
**Claim reward** 
- Actual: If user does not claim the reward regularly, this request action on the SubWallet will be unsuccessful. However, user claim successfully on astar app

**Comment by NamPhamc99** [comment]
Astar:
- [ ] Notify user when there's staking reward to claim
- [ ] Show claimed amount after claiming
- [ ] Show claiming history

**Comment by NamPhamc99** [comment]
- [ ] Support cases when controller account is different from stash account
- [ ] Check cases with ledger account

**Comment by sokol142** [comment]
- [ ] Allows the nominator to stake more in case the nominators count reaches the maximum value

**Comment by sokol142** [comment]
Improved on the new UI version.
