### ISSUE TITLE
Auto Import account from Polkadot js wallet to SubWallet

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#89]
**Is your feature request related to a problem? Please describe.**
Migrate account from Polkadot js wallet to SubWallet

After installing SubWallet, have an option for users to automatically import all account from Polkadot JS to SubWallet without json file

**Comment by vantrong291** [comment]
### Describe the solution you'd like
When users install Polkadot.js Wallet Extension, data about accounts is encrypted and stored in the extension's data directory. The location of this folder depends on the browser type and Operating System, for example for Google Chrome browser:
**Windows**
C:\Users\\<Your_User_Name>\AppData\Local\Google\Chrome\User Data\Default\Local\ Extension\ Settings/mopnmbcafieddcagagdcbnhejhlodfdd/000003.log 
**Linux**
~/.config/google-chrome/Default/Local\ Extension\ Settings/mopnmbcafieddcagagdcbnhejhlodfdd/000003.log
**MacOS**
~/Library/Application\ Support/Google/Chrome/Default/Local\ Extension\ Settings/mopnmbcafieddcagagdcbnhejhlodfdd/000003.log

> _mopnmbcafieddcagagdcbnhejhlodfdd_ is id of Polkadot.js Wallet Extension

**Here is an example of the contents of a 000003.log file:**

![image](https://user-images.githubusercontent.com/32742729/162154396-338b4aa4-b7ff-427e-90a2-f66794e50612.png)

If there are only 1-2 accounts on Polkadot wallet, it's okay, but with more accounts, entering the pass for each one is also quite inconvenient.
In this case, using the export all to json function will be faster because you only need to enter the password once.
